# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class HelloInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        """
   {}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class HelloOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        """
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "message": {
      "type": "string",
      "title": "Message",
      "order": 1
    }
  },
  "required": [
    "message"
  ]
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
