# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    HOSTNAME = "hostname"
    PORT = "port"
    USERNAME = "username"
    

class ConnectionSchema(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "hostname": {
      "type": "string",
      "title": "Host",
      "description": "Enter the hostname",
      "order": 1
    },
    "port": {
      "type": "integer",
      "title": "Port",
      "description": "Enter the port",
      "default": 80,
      "order": 2
    },
    "username": {
      "type": "string",
      "title": "Username",
      "description": "Enter the username",
      "order": 3
    }
  },
  "required": [
    "hostname",
    "port",
    "username"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
