# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Emit say hello message"


class Input:
    NAME = "name"
    

class Output:
    MESSAGE = "message"
    

class SayHelloInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "name": {
      "type": "string",
      "title": "Name",
      "description": "Name to say hello to",
      "order": 1
    }
  },
  "required": [
    "name"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class SayHelloOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "message": {
      "type": "string",
      "title": "Message",
      "order": 1
    }
  },
  "required": [
    "message"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
