#!/usr/bin/env python
# GENERATED BY KOMAND SDK - DO NOT EDIT
from tests.integration.plugin import run_action, run_trigger


def test_simple_action():
    run_action('./tests/integration/action/input.json', './tests/integration/action/output.json')


def test_simple_trigger():
    run_trigger('./tests/integration/trigger/input.json', './tests/integration/trigger/output.json')
