#!/usr/bin/env python
# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand


Name = 'HelloWorld'
Vendor = 'komand'
Version = '1.0.0'
Description = 'Hello World plugin'


input_schema = {
    'type': 'object',
    'properties': {
        'name': {
            'type': 'string'
        }
    },
    'required': ['name']
}

output_schema = {
    'type': 'object',
    'properties': {
        'text': {
            'type': 'string'
        }
    },
    'required': ['text']
}


class KomandFoobar(komand.Plugin):
    def __init__(self):
        super(self.__class__, self).__init__(
            name=Name,
            vendor=Vendor,
            version=Version,
            description=Description,
            connection=komand.Connection(input=komand.Input(schema={
                'type': 'object',
                'properties': {
                    'greeting': {
                        'type': 'string'
                    }
                },
                'required': ['greeting']
            }))
        )

        self.add_action(komand.Action(
            name='action',
            description='description',
            input=komand.Input(schema=input_schema),
            output=komand.Output(schema=output_schema),
        ))

        self.add_trigger(komand.Trigger(
            name='trigger',
            description='description',
            input=komand.Input(schema=input_schema),
            output=komand.Output(schema=output_schema),
        ))


def test_action():
    pass


def test_trigger():
    pass
