# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class ConnectionSchema(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "greeting": {
      "type": "string",
      "title": "Greeting",
      "description": "A greeting",
      "default": "Hello, {}!",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
