# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(
    name="foobar-komand-plugin",
    version="0.1.0",
    description="foobar plugin.",
    author="komand",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=[
        "insightconnect-plugin-runtime"
    ],  # Add third-party dependencies to requirements.txt, not here!
    scripts=["bin/komand_foobar"],
)
