# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Raise PluginException or ConnectionTestException"


class Input:
    TYPE = "type"
    

class Output:
    SUCCESS = "success"
    

class RaiseErrorInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "type": {
      "type": "string",
      "title": "Type",
      "description": "Exception type",
      "enum": [
        "Exception",
        "PluginException",
        "ConnectionTestException"
      ],
      "order": 1
    }
  },
  "required": [
    "type"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class RaiseErrorOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "order": 1
    }
  },
  "required": [
    "success"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
